server:
    port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.xudd.asj.validate.service.model  # 注意：对应实体类的路径

spring:
  # mysql数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/validate_server?zeroDateTimeBehavior=convertToNull&useUnicode=true&amp;characterEncoding=utf-8&allowMultiQueries=true&tinyInt1isBit=false
    username: root
    password: 1234
    initialization-mode: never
    schema: classpath:/db/schema-dev.sql
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/db/data-dev.sql
#    continue-on-error: false
  #druid 阿里连接池配置
  # 初始化时建立物理连接的个数
    initialSize: 1
    minIdle: 3
    maxActive: 20
  # 配置获取连接等待超时的时间
    maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
  # 验证连接有效与否的SQL，不同的数据配置不同
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  # 属性类型是字符串，通过别名的方式配置扩展插件，
  # 常用的插件有：
  # 监控统计用的filter:stat
  # 日志用的filter:log4j
  # 防御sql注入的filter:wall
    filters: stat,wall,slf4j
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  #AOP配置
  aop:
    auto: true

logging:
  config: classpath:logback-spring.xml